# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='greet.proto',
  package='greet',
  syntax='proto3',
  serialized_options=b'\252\002\013GrpcGreeter',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bgreet.proto\x12\x05greet\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x07\n\x05image\"\x0e\n\x0cHalconWindow\"\x17\n\x07_String\x12\x0c\n\x04Text\x18\x01 \x01(\t2\xb2\x01\n\x07Greeter\x12\x37\n\rPrintfMessage\x12\x0e.greet._String\x1a\x16.google.protobuf.Empty\x12\x39\n\x0f\x41\x64\x64HalconWindow\x12\x16.google.protobuf.Empty\x1a\x0e.greet._String\x12\x33\n\tDispayObj\x12\x0c.greet.image\x1a\x16.google.protobuf.Empty(\x01\x42\x0e\xaa\x02\x0bGrpcGreeterb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_IMAGE = _descriptor.Descriptor(
  name='image',
  full_name='greet.image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=90,
)


_HALCONWINDOW = _descriptor.Descriptor(
  name='HalconWindow',
  full_name='greet.HalconWindow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=106,
)


__STRING = _descriptor.Descriptor(
  name='_String',
  full_name='greet._String',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Text', full_name='greet._String.Text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=131,
)

DESCRIPTOR.message_types_by_name['image'] = _IMAGE
DESCRIPTOR.message_types_by_name['HalconWindow'] = _HALCONWINDOW
DESCRIPTOR.message_types_by_name['_String'] = __STRING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

image = _reflection.GeneratedProtocolMessageType('image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.image)
  })
_sym_db.RegisterMessage(image)

HalconWindow = _reflection.GeneratedProtocolMessageType('HalconWindow', (_message.Message,), {
  'DESCRIPTOR' : _HALCONWINDOW,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.HalconWindow)
  })
_sym_db.RegisterMessage(HalconWindow)

_String = _reflection.GeneratedProtocolMessageType('_String', (_message.Message,), {
  'DESCRIPTOR' : __STRING,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet._String)
  })
_sym_db.RegisterMessage(_String)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='greet.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=134,
  serialized_end=312,
  methods=[
  _descriptor.MethodDescriptor(
    name='PrintfMessage',
    full_name='greet.Greeter.PrintfMessage',
    index=0,
    containing_service=None,
    input_type=__STRING,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddHalconWindow',
    full_name='greet.Greeter.AddHalconWindow',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=__STRING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DispayObj',
    full_name='greet.Greeter.DispayObj',
    index=2,
    containing_service=None,
    input_type=_IMAGE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
